#!/usr/bin/with-contenv /bin/bash

while [ ! -f /tmp/state/10-postfix-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/09-rsyslog ]; then
  mkdir -p /tmp/state
  echo 'Initialization Complete' >/tmp/state/10-postfix
fi

# Check Postfix configuration

postconf -c /opt/postfix/conf

if [[ $? != 0 ]]; then
  echo "Postfix configuration error, refusing to start."
  exit 1
else
  echo '** [postfix] Starting postfix'
  exec /usr/sbin/postfix -c /opt/etc/postfix/conf start-fg
fi


